// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	twitterclone "twitterclone"
)

// AuthTokenService is an autogenerated mock type for the AuthTokenService type
type AuthTokenService struct {
	mock.Mock
}

// CreateAccessToken provides a mock function with given fields: ctx, user
func (_m *AuthTokenService) CreateAccessToken(ctx context.Context, user twitterclone.User) (string, error) {
	ret := _m.Called(ctx, user)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, twitterclone.User) (string, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, twitterclone.User) string); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, twitterclone.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateRefreshAccessToken provides a mock function with given fields: ctx, user, tokenID
func (_m *AuthTokenService) CreateRefreshAccessToken(ctx context.Context, user twitterclone.User, tokenID string) (string, error) {
	ret := _m.Called(ctx, user, tokenID)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, twitterclone.User, string) (string, error)); ok {
		return rf(ctx, user, tokenID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, twitterclone.User, string) string); ok {
		r0 = rf(ctx, user, tokenID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, twitterclone.User, string) error); ok {
		r1 = rf(ctx, user, tokenID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParseToken provides a mock function with given fields: ctx, payload
func (_m *AuthTokenService) ParseToken(ctx context.Context, payload string) (twitterclone.AuthToken, error) {
	ret := _m.Called(ctx, payload)

	var r0 twitterclone.AuthToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (twitterclone.AuthToken, error)); ok {
		return rf(ctx, payload)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) twitterclone.AuthToken); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(twitterclone.AuthToken)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParseTokenFromRequest provides a mock function with given fields: ctx, r
func (_m *AuthTokenService) ParseTokenFromRequest(ctx context.Context, r *http.Request) (twitterclone.AuthToken, error) {
	ret := _m.Called(ctx, r)

	var r0 twitterclone.AuthToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *http.Request) (twitterclone.AuthToken, error)); ok {
		return rf(ctx, r)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *http.Request) twitterclone.AuthToken); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Get(0).(twitterclone.AuthToken)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *http.Request) error); ok {
		r1 = rf(ctx, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAuthTokenService interface {
	mock.TestingT
	Cleanup(func())
}

// NewAuthTokenService creates a new instance of AuthTokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthTokenService(t mockConstructorTestingTNewAuthTokenService) *AuthTokenService {
	mock := &AuthTokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
