// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"
	twitterclone "twitterclone"

	mock "github.com/stretchr/testify/mock"
)

// TweetRepo is an autogenerated mock type for the TweetRepo type
type TweetRepo struct {
	mock.Mock
}

// All provides a mock function with given fields: ctx
func (_m *TweetRepo) All(ctx context.Context) ([]twitterclone.Tweet, error) {
	ret := _m.Called(ctx)

	var r0 []twitterclone.Tweet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]twitterclone.Tweet, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []twitterclone.Tweet); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]twitterclone.Tweet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, input
func (_m *TweetRepo) Create(ctx context.Context, input twitterclone.Tweet) (twitterclone.Tweet, error) {
	ret := _m.Called(ctx, input)

	var r0 twitterclone.Tweet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, twitterclone.Tweet) (twitterclone.Tweet, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, twitterclone.Tweet) twitterclone.Tweet); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(twitterclone.Tweet)
	}

	if rf, ok := ret.Get(1).(func(context.Context, twitterclone.Tweet) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *TweetRepo) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetById provides a mock function with given fields: ctx, id
func (_m *TweetRepo) GetById(ctx context.Context, id string) (twitterclone.Tweet, error) {
	ret := _m.Called(ctx, id)

	var r0 twitterclone.Tweet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (twitterclone.Tweet, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) twitterclone.Tweet); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(twitterclone.Tweet)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewTweetRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewTweetRepo creates a new instance of TweetRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTweetRepo(t mockConstructorTestingTNewTweetRepo) *TweetRepo {
	mock := &TweetRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
